set_property PACKAGE_PIN F12 [get_ports TMDS_0_0_clk_p]
set_property PACKAGE_PIN E13 [get_ports TMDS_0_0_clk_n]
set_property PACKAGE_PIN E11 [get_ports {TMDS_0_0_data_p[0]}]
set_property PACKAGE_PIN E12 [get_ports {TMDS_0_0_data_n[0]}]
set_property PACKAGE_PIN G15 [get_ports {TMDS_0_0_data_p[1]}]
set_property PACKAGE_PIN F15 [get_ports {TMDS_0_0_data_n[1]}]
set_property PACKAGE_PIN F13 [get_ports {TMDS_0_0_data_p[2]}]
set_property PACKAGE_PIN F14 [get_ports {TMDS_0_0_data_n[2]}]
set_property IOSTANDARD TMDS_33 [get_ports TMDS_*]

set_property PACKAGE_PIN N11 [get_ports CSI_C_P]
set_property PACKAGE_PIN N12 [get_ports CSI_C_N]
set_property PACKAGE_PIN R7 [get_ports {CSI_D_P[0]}]
set_property PACKAGE_PIN R8 [get_ports {CSI_D_N[0]}]
set_property PACKAGE_PIN R12 [get_ports {CSI_D_P[1]}]
set_property PACKAGE_PIN R13 [get_ports {CSI_D_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports CSI_*]
set_property PACKAGE_PIN N8 [get_ports {CLP_D_N[0]}]
set_property PACKAGE_PIN N7 [get_ports {CLP_D_P[0]}]
set_property PACKAGE_PIN P14 [get_ports {CLP_D_N[1]}]
set_property PACKAGE_PIN P13 [get_ports {CLP_D_P[1]}]
set_property PACKAGE_PIN R11 [get_ports CLP_C_N]
set_property PACKAGE_PIN P11 [get_ports CLP_C_P]
set_property IOSTANDARD HSUL_12 [get_ports CLP_*]
set_property PULLDOWN true [get_ports {CLP_D_N[1]}]
set_property PULLDOWN true [get_ports {CLP_D_N[0]}]
set_property PULLDOWN true [get_ports {CLP_D_P[1]}]
set_property PULLDOWN true [get_ports {CLP_D_P[0]}]
set_property PULLDOWN true [get_ports CLP_C_N]
set_property PULLDOWN true [get_ports CLP_C_P]
set_property INTERNAL_VREF 0.6 [get_iobanks 34]
create_clock -period 6.250 -name csi_clk -add [get_ports CSI_C_P]

set_property PACKAGE_PIN H11 [get_ports const_1]
set_property PACKAGE_PIN J11 [get_ports const_2]
set_property IOSTANDARD LVCMOS33 [get_ports const_*]

set_clock_groups -name rxbyteclk -asynchronous -group [get_clocks -of_objects [get_pins design_1_i/mipi_ip/mipi_csi2_rx_subsyst_0/U0/phy/inst/inst/bd_108c_phy_0_rx_support_i/slave_rx.bd_108c_phy_0_rx_ioi_i/clkout_buf_inst/O] -filter {IS_GENERATED && MASTER_CLOCK == csi_clk}] -group [get_clocks -of_objects [get_pins design_1_i/mipi_ip/mipi_csi2_rx_subsyst_0/U0/phy/inst/inst/bd_108c_phy_0_rx_support_i/slave_rx.bd_108c_phy_0_rx_ioi_i/clkout_buf_inst/O] -filter {IS_GENERATED && MASTER_CLOCK == CSI_C_P}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
