vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/axi_vip_v1_1_8
vlib modelsim_lib/msim/processing_system7_vip_v1_0_10
vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/axi_register_slice_v2_1_22
vlib modelsim_lib/msim/fifo_generator_v13_2_5
vlib modelsim_lib/msim/axi_data_fifo_v2_1_21
vlib modelsim_lib/msim/axi_crossbar_v2_1_23
vlib modelsim_lib/msim/axis_register_slice_v1_1_22
vlib modelsim_lib/msim/axis_subset_converter_v1_1_22
vlib modelsim_lib/msim/mipi_dphy_v4_3_0
vlib modelsim_lib/msim/axis_dwidth_converter_v1_1_21
vlib modelsim_lib/msim/vfb_v1_0_16
vlib modelsim_lib/msim/v_demosaic_v1_1_0
vlib modelsim_lib/msim/v_axi4s_vid_out_v4_0_11
vlib modelsim_lib/msim/v_tc_v6_2_1
vlib modelsim_lib/msim/xlconstant_v1_1_7
vlib modelsim_lib/msim/lib_fifo_v1_0_14
vlib modelsim_lib/msim/blk_mem_gen_v8_4_4
vlib modelsim_lib/msim/lib_bmg_v1_0_13
vlib modelsim_lib/msim/axi_datamover_v5_1_24
vlib modelsim_lib/msim/axi_vdma_v6_3_10
vlib modelsim_lib/msim/axi_protocol_converter_v2_1_22

vmap axi_vip_v1_1_8 modelsim_lib/msim/axi_vip_v1_1_8
vmap processing_system7_vip_v1_0_10 modelsim_lib/msim/processing_system7_vip_v1_0_10
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap axi_register_slice_v2_1_22 modelsim_lib/msim/axi_register_slice_v2_1_22
vmap fifo_generator_v13_2_5 modelsim_lib/msim/fifo_generator_v13_2_5
vmap axi_data_fifo_v2_1_21 modelsim_lib/msim/axi_data_fifo_v2_1_21
vmap axi_crossbar_v2_1_23 modelsim_lib/msim/axi_crossbar_v2_1_23
vmap axis_register_slice_v1_1_22 modelsim_lib/msim/axis_register_slice_v1_1_22
vmap axis_subset_converter_v1_1_22 modelsim_lib/msim/axis_subset_converter_v1_1_22
vmap mipi_dphy_v4_3_0 modelsim_lib/msim/mipi_dphy_v4_3_0
vmap axis_dwidth_converter_v1_1_21 modelsim_lib/msim/axis_dwidth_converter_v1_1_21
vmap vfb_v1_0_16 modelsim_lib/msim/vfb_v1_0_16
vmap v_demosaic_v1_1_0 modelsim_lib/msim/v_demosaic_v1_1_0
vmap v_axi4s_vid_out_v4_0_11 modelsim_lib/msim/v_axi4s_vid_out_v4_0_11
vmap v_tc_v6_2_1 modelsim_lib/msim/v_tc_v6_2_1
vmap xlconstant_v1_1_7 modelsim_lib/msim/xlconstant_v1_1_7
vmap lib_fifo_v1_0_14 modelsim_lib/msim/lib_fifo_v1_0_14
vmap blk_mem_gen_v8_4_4 modelsim_lib/msim/blk_mem_gen_v8_4_4
vmap lib_bmg_v1_0_13 modelsim_lib/msim/lib_bmg_v1_0_13
vmap axi_datamover_v5_1_24 modelsim_lib/msim/axi_datamover_v5_1_24
vmap axi_vdma_v6_3_10 modelsim_lib/msim/axi_vdma_v6_3_10
vmap axi_protocol_converter_v2_1_22 modelsim_lib/msim/axi_protocol_converter_v2_1_22

vlog -work axi_vip_v1_1_8  -incr -sv -L axi_vip_v1_1_8 -L processing_system7_vip_v1_0_10 -L smartconnect_v1_0 -L mipi_dphy_v4_3_0 -L xilinx_vip "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_10  -incr -sv -L axi_vip_v1_1_8 -L processing_system7_vip_v1_0_10 -L smartconnect_v1_0 -L mipi_dphy_v4_3_0 -L xilinx_vip "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \

vlog -work axi_register_slice_v2_1_22  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work fifo_generator_v13_2_5  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_5  -93 \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_5  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \

vlog -work axi_data_fifo_v2_1_21  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_23  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_xbar_6/sim/design_1_xbar_6.v" \

vlog -work axis_register_slice_v1_1_22  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ebcc/hdl/axis_register_slice_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_1_6/hdl/tdata_design_1_axis_subset_converter_1_6.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_1_6/hdl/tuser_design_1_axis_subset_converter_1_6.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_1_6/hdl/tstrb_design_1_axis_subset_converter_1_6.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_1_6/hdl/tkeep_design_1_axis_subset_converter_1_6.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_1_6/hdl/tid_design_1_axis_subset_converter_1_6.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_1_6/hdl/tdest_design_1_axis_subset_converter_1_6.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_1_6/hdl/tlast_design_1_axis_subset_converter_1_6.v" \

vlog -work axis_subset_converter_v1_1_22  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/69d9/hdl/axis_subset_converter_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_1_6/hdl/top_design_1_axis_subset_converter_1_6.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_1_6/sim/design_1_axis_subset_converter_1_6.v" \
"../../../bd/design_1/ip/design_1_clk_wiz_1_2/design_1_clk_wiz_1_2_clk_wiz.v" \
"../../../bd/design_1/ip/design_1_clk_wiz_1_2/design_1_clk_wiz_1_2.v" \

vcom -work xil_defaultlib  -93 \
"../../../bd/design_1/ip/design_1_ila_0_2/sim/design_1_ila_0_2.vhd" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_0/sim/bd_108c_r_sync_0.vhd" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_1/sim/bd_108c_rx_0.v" \

vlog -work mipi_dphy_v4_3_0  -incr -sv -L axi_vip_v1_1_8 -L processing_system7_vip_v1_0_10 -L smartconnect_v1_0 -L mipi_dphy_v4_3_0 -L xilinx_vip "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/543b/hdl/mipi_dphy_v4_3_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_2/bd_108c_phy_0/support/bd_108c_phy_0_support.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_2/bd_108c_phy_0_c1.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_2/bd_108c_phy_0_core.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_2/bd_108c_phy_0.v" \

vlog -work axis_dwidth_converter_v1_1_21  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/6614/hdl/axis_dwidth_converter_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/ip_0/sim/bd_108c_vfb_0_0_axis_converter.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0/src/verilog/bd_108c_vfb_0_0_fifo.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0/src/verilog/bd_108c_vfb_0_0_axis_ycomp_dconverter.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0/src/verilog/bd_108c_vfb_0_0_fifo_ycomp.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0/src/verilog/bd_108c_vfb_0_0_YUV420_DT_Demux.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0/src/verilog/bd_108c_vfb_0_0_YUV420_DT_Mux.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0/src/verilog/bd_108c_vfb_0_0_YUV420_vc4_mux.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0/src/verilog/bd_108c_vfb_0_0_YUV420_vc4_demux.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0/src/verilog/bd_108c_vfb_0_0_YUV420_vc16_mux.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0/src/verilog/bd_108c_vfb_0_0_YUV420_vc16_demux.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0/src/verilog/bd_108c_vfb_0_0_fifo_yuv.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0/src/verilog/bd_108c_vfb_0_0_fifo_sb.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0/src/verilog/bd_108c_vfb_0_0_axis_dconverter.v" \

vlog -work vfb_v1_0_16  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/9d30/hdl/vfb_v1_0_rfs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0_core.v" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/ip/ip_3/bd_108c_vfb_0_0.v" \

vcom -work xil_defaultlib  -93 \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/bd_0/sim/bd_108c.vhd" \
"../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_2/sim/design_1_mipi_csi2_rx_subsyst_0_2.vhd" \
"../../../bd/design_1/ip/design_1_rst_ps8_0_100M1_2/sim/design_1_rst_ps8_0_100M1_2.vhd" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_AXIvideo2MultiBayer.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_Block_split1_proc.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_CTRL_s_axi.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_Debayer.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_DebayerG.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_DebayerG_DIV1_TABLE.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_DebayerG_DIV2_TABLE.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_DebayerG_linebuf_yuv_val_V_0.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_DebayerRandBatG.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_DebayerRatBorBatR.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_DebayerRatBorBatR_lineBuffer_val_V_0.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_fifo_w8_d2_S.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_fifo_w16_d2_S.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_fifo_w16_d2_S_x.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_fifo_w24_d2_S.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_fifo_w24_d2_S_x.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_hls_deadlock_detection_unit.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_mac_muladd_12s_10ns_22s_23_4_1.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_mul_mul_12s_10ns_22_4_1.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_mul_mul_18s_8ns_18_4_1.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_mul_mul_18s_9ns_18_4_1.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_MultiPixStream2AXIvideo.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_mux_32_8_1_1.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_reg_unsigned_short_s.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_regslice_both.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_start_for_Block_split1_proc_U0.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_start_for_DebayerRandBatG_U0.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_start_for_DebayerRatBorBatR_U0.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_start_for_MultiPixStream2AXIvideo_U0.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_start_for_v_demosaic_entry48_U0.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_start_for_ZipperRemoval_U0.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_v_demosaic_entry5.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_v_demosaic_entry48.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_ZipperRemoval.v" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog/design_1_v_demosaic_0_2_v_demosaic.v" \

vlog -work v_demosaic_v1_1_0  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/v_demosaic_v1_1_rfs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_v_demosaic_0_2/sim/design_1_v_demosaic_0_2.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tdata_design_1_axis_subset_converter_0_0.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tuser_design_1_axis_subset_converter_0_0.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tstrb_design_1_axis_subset_converter_0_0.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tkeep_design_1_axis_subset_converter_0_0.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tid_design_1_axis_subset_converter_0_0.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tdest_design_1_axis_subset_converter_0_0.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tlast_design_1_axis_subset_converter_0_0.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/top_design_1_axis_subset_converter_0_0.v" \
"../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/sim/design_1_axis_subset_converter_0_0.v" \
"../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
"../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \

vcom -work xil_defaultlib  -93 \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/20df/src/ClockGen.vhd" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/20df/src/SyncAsync.vhd" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/20df/src/SyncAsyncReset.vhd" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/20df/src/DVI_Constants.vhd" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/20df/src/OutputSERDES.vhd" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/20df/src/TMDS_Encoder.vhd" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/20df/src/rgb2dvi.vhd" \
"../../../bd/design_1/ip/design_1_rgb2dvi_0_0/sim/design_1_rgb2dvi_0_0.vhd" \
"../../../bd/design_1/ip/design_1_rst_ps8_0_100M1_3/sim/design_1_rst_ps8_0_100M1_3.vhd" \

vlog -work v_axi4s_vid_out_v4_0_11  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1a1e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/sim/design_1_v_axi4s_vid_out_0_0.v" \

vcom -work v_tc_v6_2_1  -93 \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/cd2e/hdl/v_tc_v6_2_vh_rfs.vhd" \

vcom -work xil_defaultlib  -93 \
"../../../bd/design_1/ip/design_1_v_tc_0_0/sim/design_1_v_tc_0_0.vhd" \

vlog -work xlconstant_v1_1_7  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v" \
"../../../bd/design_1/ip/design_1_xbar_7/sim/design_1_xbar_7.v" \

vcom -work lib_fifo_v1_0_14  -93 \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \

vlog -work blk_mem_gen_v8_4_4  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \

vcom -work lib_bmg_v1_0_13  -93 \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_24  -93 \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/4ab6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vlog -work axi_vdma_v6_3_10  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl/axi_vdma_v6_3_rfs.v" \

vcom -work axi_vdma_v6_3_10  -93 \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl/axi_vdma_v6_3_rfs.vhd" \

vcom -work xil_defaultlib  -93 \
"../../../bd/design_1/ip/design_1_axi_vdma_0_0/sim/design_1_axi_vdma_0_0.vhd" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/sim/bd_48ac.v" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_48ac_one_0.v" \

vcom -work xil_defaultlib  -93 \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_48ac_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -incr -sv -L axi_vip_v1_1_8 -L processing_system7_vip_v1_0_10 -L smartconnect_v1_0 -L mipi_dphy_v4_3_0 -L xilinx_vip "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_48ac_arsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_48ac_rsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_48ac_awsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_48ac_wsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_48ac_bsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_48ac_s00mmu_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_48ac_s00tr_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_48ac_s00sic_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_48ac_s00a2s_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_48ac_sarn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_48ac_srn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_48ac_s01mmu_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_48ac_s01tr_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_48ac_s01sic_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_48ac_s01a2s_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_48ac_sawn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_48ac_swn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_48ac_sbn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_48ac_m00s2a_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_48ac_m00arn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_48ac_m00rn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_48ac_m00awn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_48ac_m00wn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_48ac_m00bn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_48ac_m00e_0.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/sim/design_1_smartconnect_0_0.v" \

vcom -work xil_defaultlib  -93 \
"../../../bd/design_1/sim/design_1.vhd" \

vlog -work axi_protocol_converter_v2_1_22  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/34f8/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/d0f7" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/88d7/hdl" "+incdir+../../../bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/7860/hdl" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/25b7/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/896c/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" "+incdir+../../../../ZynqBerryZero.gen/sources_1/bd/design_1/ip/design_1_v_demosaic_0_2/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
"../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
"../../../bd/design_1/ip/design_1_xlconstant_0_1/sim/design_1_xlconstant_0_1.v" \

vlog -work xil_defaultlib \
"glbl.v"

